"""Validate MeetingWatch's published active and history datasets.

The validator is intentionally dependency-free so it can run in the scraper
workflow, CI, and post-deploy smoke checks.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo


DENVER = ZoneInfo("America/Denver")


def _load_object(path: Path) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path}: expected a top-level JSON object")
    if not isinstance(payload.get("meetings"), list):
        raise ValueError(f"{path}: expected a meetings array")
    return payload


def _parse_utc(value: object) -> datetime | None:
    text = str(value or "").strip()
    if not text:
        return None
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        return None
    return parsed.astimezone(timezone.utc)


def _parse_date(value: object) -> date | None:
    try:
        return date.fromisoformat(str(value or "").strip())
    except ValueError:
        return None


def _identity(meeting: dict) -> str:
    return str(meeting.get("id") or "").strip() or "|".join(
        str(meeting.get(key) or "").strip().lower()
        for key in ("city", "meeting_type", "date", "start_time_local", "source")
    )


def _validate_editorial(meeting: dict, label: str) -> list[str]:
    """Validate the public trust contract when editorial fields are present."""
    errors: list[str] = []
    status = meeting.get("agenda_briefing_status")
    if status is None:
        return errors
    briefing = meeting.get("agenda_briefing")
    legacy = meeting.get("agenda_summary") or []
    provenance = meeting.get("agenda_briefing_provenance") or {}
    if status == "verified":
        if not isinstance(briefing, dict):
            return [f"{label}: verified briefing is missing"]
        items = briefing.get("items")
        if not isinstance(items, list) or not 1 <= len(items) <= 8:
            errors.append(f"{label}: verified briefing must contain 1-8 stories")
        else:
            for item_index, item in enumerate(items):
                if not isinstance(item, dict):
                    errors.append(f"{label}: briefing item {item_index} is not an object")
                    continue
                for field in ("headline", "action", "why_it_matters", "evidence"):
                    if not str(item.get(field) or "").strip():
                        errors.append(f"{label}: briefing item {item_index} lacks {field}")
                if item.get("priority") not in {"top", "notable"}:
                    errors.append(f"{label}: briefing item {item_index} has invalid priority")
        if provenance.get("validation") != "source-grounded":
            errors.append(f"{label}: verified briefing lacks source-grounded provenance")
    else:
        if briefing:
            errors.append(f"{label}: unverified briefing must not be published")
        if legacy:
            errors.append(f"{label}: unverified legacy summary must be empty")
    return errors


def validate_payloads(
    meetings_payload: dict,
    history_payload: dict,
    *,
    now_utc: datetime,
    max_age_hours: float,
    min_active: int,
) -> list[str]:
    errors: list[str] = []
    now_utc = now_utc.astimezone(timezone.utc)
    today_denver = now_utc.astimezone(DENVER).date()

    generated_at = _parse_utc(meetings_payload.get("generated_at_utc"))
    if generated_at is None:
        errors.append("meetings.json: missing or invalid generated_at_utc")
    else:
        age = now_utc - generated_at
        if age < timedelta(minutes=-15):
            errors.append("meetings.json: generated_at_utc is unexpectedly in the future")
        elif age > timedelta(hours=max_age_hours):
            errors.append(
                f"meetings.json: data is stale ({age.total_seconds() / 3600:.1f}h old; "
                f"limit {max_age_hours:g}h)"
            )

    history_generated_at = _parse_utc(history_payload.get("generated_at_utc"))
    if history_generated_at is None:
        errors.append("history.json: missing or invalid generated_at_utc")
    elif generated_at is not None and abs(history_generated_at - generated_at) > timedelta(minutes=5):
        errors.append("meetings.json and history.json were not generated by the same run")

    active = meetings_payload["meetings"]
    history = history_payload["meetings"]
    if len(active) < min_active:
        errors.append(f"meetings.json: expected at least {min_active} active meeting(s), found {len(active)}")

    active_ids: set[str] = set()
    for index, meeting in enumerate(active):
        if not isinstance(meeting, dict):
            errors.append(f"meetings.json: meetings[{index}] is not an object")
            continue
        meeting_date = _parse_date(meeting.get("date"))
        if meeting_date is None:
            errors.append(f"meetings.json: meetings[{index}] has a missing/invalid date")
        elif meeting_date < today_denver:
            errors.append(
                f"meetings.json: meetings[{index}] is past ({meeting_date.isoformat()} < "
                f"{today_denver.isoformat()})"
            )
        identity = _identity(meeting)
        if identity in active_ids:
            errors.append(f"meetings.json: duplicate meeting identity {identity!r}")
        active_ids.add(identity)
        errors.extend(_validate_editorial(meeting, f"meetings.json: meetings[{index}]"))

    retention_days = int(history_payload.get("retention_days") or 60)
    cutoff = today_denver - timedelta(days=retention_days)
    history_ids: set[str] = set()
    for index, meeting in enumerate(history):
        if not isinstance(meeting, dict):
            errors.append(f"history.json: meetings[{index}] is not an object")
            continue
        meeting_date = _parse_date(meeting.get("date"))
        if meeting_date is None:
            errors.append(f"history.json: meetings[{index}] has a missing/invalid date")
        elif meeting_date >= today_denver:
            errors.append(
                f"history.json: meetings[{index}] is not historical ({meeting_date.isoformat()})"
            )
        elif meeting_date < cutoff:
            errors.append(
                f"history.json: meetings[{index}] exceeds {retention_days}-day retention "
                f"({meeting_date.isoformat()} < {cutoff.isoformat()})"
            )
        identity = _identity(meeting)
        if identity in history_ids:
            errors.append(f"history.json: duplicate meeting identity {identity!r}")
        history_ids.add(identity)

    overlap = active_ids & history_ids
    if overlap:
        errors.append(f"active/history datasets overlap for {len(overlap)} meeting(s)")

    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--meetings", type=Path, default=Path("data/meetings.json"))
    parser.add_argument("--history", type=Path, default=Path("data/history.json"))
    parser.add_argument("--max-age-hours", type=float, default=36)
    parser.add_argument("--min-active", type=int, default=1)
    parser.add_argument(
        "--now-utc",
        help="ISO timestamp override for deterministic tests/diagnostics",
    )
    args = parser.parse_args(argv)

    try:
        meetings_payload = _load_object(args.meetings)
        history_payload = _load_object(args.history)
        now_utc = _parse_utc(args.now_utc) if args.now_utc else datetime.now(timezone.utc)
        if now_utc is None:
            raise ValueError("--now-utc must be a timezone-aware ISO timestamp")
        errors = validate_payloads(
            meetings_payload,
            history_payload,
            now_utc=now_utc,
            max_age_hours=args.max_age_hours,
            min_active=args.min_active,
        )
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    print(
        f"OK: {len(meetings_payload['meetings'])} active meeting(s), "
        f"{len(history_payload['meetings'])} historical meeting(s); data is fresh"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
